#pragma once

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include "plugincore/params.h"

// The text preset format shared by every plugin built on it: the same syntax, the
// same real-world units, the same grouping by module heading. Only the plugin's
// name, its file extension and its parameter table differ, and those arrive in
// a PresetContext.

namespace plugincore {

// What the preset code needs to know about the plugin it is working for.
struct PresetContext {
   const char *pluginName;      // display name, e.g. "RainyDay"
   const char *presetExtension; // file extension without the dot, e.g. "rainyday"
   const ParamDesc *table;
   uint32_t paramCount;
};

// One factory preset compiled into the plugin binary, as generated by
// shared/cmake/embed_presets.cmake.
struct BuiltinPreset {
   const char *loadKey;
   const char *text;
};

// A parsed preset: metadata plus the raw (host-facing) parameter values it
// wants to set. Parameters absent from the file keep their current value.
struct PresetData {
   std::string name;
   std::string author;
   std::string description;
   std::vector<std::string> features;
   std::vector<std::pair<uint32_t, double>> values;
};

// Absolute path to the "presets" directory that sits next to the loaded
// plugin binary, or an empty string if it cannot be determined.
std::string factoryPresetDir(const PresetContext &ctx);

// Absolute path to the per-user preset directory
// ($XDG_CONFIG_HOME/<PluginName>/presets). Not created by the plugin.
std::string userPresetDir(const PresetContext &ctx);

// Parses the text preset format. Returns false and fills `error` on malformed
// input.
bool parsePreset(const PresetContext &ctx, const char *text, size_t length, PresetData &out,
                 std::string &error);
bool parsePresetFile(const PresetContext &ctx, const std::string &path, PresetData &out,
                     std::string &error);

// Writes a preset back out in the format parsePreset() reads: real-world units,
// grouped under the same module headings the factory library uses.
std::string formatPreset(const PresetContext &ctx, const PresetData &preset);

// Turns a display name into the file it should be saved as, inside the user
// preset directory. Empty if that directory cannot be determined.
std::string userPresetPath(const PresetContext &ctx, const std::string &name);

// The same, in a named folder under the user preset directory. An empty
// folder is the directory itself, so this is a superset of the call above.
//
// Folders are one level deep on purpose: a preset library is a shelf, not a
// filesystem, and a tree deep enough to get lost in is a tree somebody will
// get lost in. The folder name is sanitised exactly as the preset name is.
std::string userPresetPathIn(const PresetContext &ctx, const std::string &folder,
                             const std::string &name);

// Turns a display name into something safe to use as a file or folder name.
std::string presetFileStem(const std::string &name);

// ------------------------------------------------------------------- packs
//
// A preset pack is one text file holding a whole folder's worth of presets, so
// a library can be handed to somebody else as a single file. It is the preset
// format again with a separator line between the presets, which means it can
// be read, diffed and edited by hand like everything else here -- and that a
// preset carrying plugin-specific lines the shared format knows nothing about
// (SaeureKiste's patterns, for instance) survives a round trip, because a pack
// carries each preset's *text* rather than a re-serialised copy of it.

struct PresetPackEntry {
   std::string name; // what the preset calls itself
   std::string text; // the preset file, verbatim
};

// The extension a pack of this plugin's presets uses: the preset extension
// with "pack" on the end, e.g. "saeurekistepack".
std::string presetPackExtension(const PresetContext &ctx);

// Where packs are kept: a "packs" directory beside the user preset directory.
// Not created by the plugin until something is written into it.
std::string presetPackDir(const PresetContext &ctx);

// Writes the pack file's text. `packName` is what the folder was called.
std::string formatPresetPack(const PresetContext &ctx, const std::string &packName,
                             const std::vector<PresetPackEntry> &entries);

// Reads one back. Returns false and fills `error` when the file is not a pack
// for this plugin; an empty pack is an error too, because importing nothing
// silently is indistinguishable from a bug.
bool parsePresetPack(const PresetContext &ctx, const std::string &text, std::string &packName,
                     std::vector<PresetPackEntry> &out, std::string &error);
bool parsePresetPackFile(const PresetContext &ctx, const std::string &path,
                         std::string &packName, std::vector<PresetPackEntry> &out,
                         std::string &error);

// Writes `text` to `path`, creating the directories above it. Returns false and
// fills `error` on failure.
bool writePresetFile(const std::string &path, const std::string &text, std::string &error);

} // namespace plugincore
