#pragma once

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include "plugincore/params.h"

// The text preset format shared by every plugin built on it: the same syntax, the
// same real-world units, the same grouping by module heading. Only the plugin's
// name, its file extension and its parameter table differ, and those arrive in
// a PresetContext.

namespace plugincore {

// What the preset code needs to know about the plugin it is working for.
struct PresetContext {
   const char *pluginName;      // display name, e.g. "RainyDay"
   const char *presetExtension; // file extension without the dot, e.g. "rainyday"
   const ParamDesc *table;
   uint32_t paramCount;
};

// One factory preset compiled into the plugin binary, as generated by
// shared/cmake/embed_presets.cmake.
struct BuiltinPreset {
   const char *loadKey;
   const char *text;
};

// A parsed preset: metadata plus the raw (host-facing) parameter values it
// wants to set. Parameters absent from the file keep their current value.
struct PresetData {
   std::string name;
   std::string author;
   std::string description;
   std::vector<std::string> features;
   std::vector<std::pair<uint32_t, double>> values;
};

// Absolute path to the "presets" directory that sits next to the loaded
// plugin binary, or an empty string if it cannot be determined.
std::string factoryPresetDir(const PresetContext &ctx);

// Absolute path to the per-user preset directory
// ($XDG_CONFIG_HOME/<PluginName>/presets). Not created by the plugin.
std::string userPresetDir(const PresetContext &ctx);

// Parses the text preset format. Returns false and fills `error` on malformed
// input.
bool parsePreset(const PresetContext &ctx, const char *text, size_t length, PresetData &out,
                 std::string &error);
bool parsePresetFile(const PresetContext &ctx, const std::string &path, PresetData &out,
                     std::string &error);

// Writes a preset back out in the format parsePreset() reads: real-world units,
// grouped under the same module headings the factory library uses.
std::string formatPreset(const PresetContext &ctx, const PresetData &preset);

// Turns a display name into the file it should be saved as, inside the user
// preset directory. Empty if that directory cannot be determined.
std::string userPresetPath(const PresetContext &ctx, const std::string &name);

// Writes `text` to `path`, creating the directories above it. Returns false and
// fills `error` on failure.
bool writePresetFile(const std::string &path, const std::string &text, std::string &error);

} // namespace plugincore
