# Turns presets/*.substrike into a C++ header of raw string literals, so the
# factory presets travel inside the plugin binary.
#
#   cmake -DPRESET_DIR=... -DOUTPUT=... -P embed_presets.cmake
#
# Written for Substrike; it does not use the shared one, as Substrike does not
# use shared/.

if(NOT PRESET_DIR OR NOT OUTPUT)
    message(FATAL_ERROR "embed_presets.cmake: PRESET_DIR and OUTPUT are required")
endif()

file(GLOB preset_files "${PRESET_DIR}/*.substrike")
list(SORT preset_files)

set(body "// Generated by cmake/embed_presets.cmake from presets/ -- do not edit.\n")
string(APPEND body "#pragma once\n\n")
string(APPEND body "namespace substrike {\n\n")
string(APPEND body "struct EmbeddedPreset\n{\n    const char* key;\n    const char* text;\n};\n\n")
string(APPEND body "inline const EmbeddedPreset kEmbeddedPresets[] = {\n")
foreach(preset_file ${preset_files})
    get_filename_component(preset_key "${preset_file}" NAME_WE)
    file(READ "${preset_file}" preset_text)
    # MSVC limits one string literal; mingw and gcc do not, and the presets
    # are a few kilobytes each.
    string(APPEND body "    {\"${preset_key}\",\n     R\"SUBSTRIKE(${preset_text})SUBSTRIKE\"},\n")
endforeach()
string(APPEND body "};\n\n")
string(APPEND body "inline constexpr int kNumEmbeddedPresets =\n")
string(APPEND body "    static_cast<int>(sizeof(kEmbeddedPresets) / sizeof(kEmbeddedPresets[0]));\n\n")
string(APPEND body "} // namespace substrike\n")

# Only rewrite on a change, so the plugin is not rebuilt for nothing.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" old)
    if(old STREQUAL body)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${body}")
