# Turns a plugin's presets/*.<ext> into a C++ header of raw string literals, so
# the plugin can serve its factory presets even when installed as a single file.
#
# Invoked as:
#
#   cmake -DPRESET_DIR=... -DOUTPUT=... -DNAMESPACE=rainyday -DPRESET_EXT=rainyday
#         -P embed_presets.cmake
#
# NAMESPACE and PRESET_EXT are required: shared by the whole suite, this script
# cannot know which plugin it is generating for, and silently defaulting either
# one would produce a header that names the wrong namespace and still compiles
# in the plugin it was copied from.

if(NOT PRESET_DIR OR NOT OUTPUT)
   message(FATAL_ERROR "embed_presets.cmake: PRESET_DIR and OUTPUT are required")
endif()
if(NOT NAMESPACE)
   message(FATAL_ERROR "embed_presets.cmake: NAMESPACE is required")
endif()
if(NOT PRESET_EXT)
   message(FATAL_ERROR "embed_presets.cmake: PRESET_EXT is required")
endif()

file(GLOB preset_files "${PRESET_DIR}/*.${PRESET_EXT}")
list(SORT preset_files)

# The raw-string delimiter has to be something a preset file cannot contain.
string(TOUPPER "${NAMESPACE}" delim)

set(body "// Generated by shared/cmake/embed_presets.cmake -- do not edit.\n")
string(APPEND body "#pragma once\n\n")
string(APPEND body "#include \"plugincore/preset.h\"\n\n")
string(APPEND body "namespace ${NAMESPACE} {\n\n")
# The struct itself is the suite's, so the array can be handed straight to the
# shared preset-discovery provider without a cast.
string(APPEND body "static const plugincore::BuiltinPreset kBuiltinPresets[] = {\n")

foreach(preset_file ${preset_files})
   get_filename_component(preset_key "${preset_file}" NAME_WE)
   file(READ "${preset_file}" preset_text)
   string(APPEND body "   {\"${preset_key}\",\n    R\"${delim}(${preset_text})${delim}\"},\n")
endforeach()

string(APPEND body "};\n\n")
string(APPEND body "static const unsigned kNumBuiltinPresets =\n")
string(APPEND body "   sizeof(kBuiltinPresets) / sizeof(kBuiltinPresets[0]);\n\n")
string(APPEND body "} // namespace ${NAMESPACE}\n")

file(WRITE "${OUTPUT}" "${body}")
